rtabmap:
  ros__parameters:
    use_sim_time: false
    frame_id: base_link
    map_frame_id: map
    odom_frame_id: odom
    subscribe_rgb: false
    subscribe_depth: false
    subscribe_rgbd: false
    subscribe_scan: false
    subscribe_scan_cloud: true
    subscribe_odom_info: false
    sync_queue_size: 20
    approx_sync: true
    use_action_topics: false
    publish_tf: true
    tf_delay: 0.2
    wait_for_transform: 0.5
    RGBD/CreateOccupancyGrid: "true"
    RGBD/NeighborLinkRefining: "true"
    Grid/DepthRayTracing: "true"
    Grid/FromDepth: "true"
    Grid/CellSize: "0.03"
    Grid/RangeMax: "6.0"
    Grid/MinClusterSize: "3"
    Grid/GlobalUpdated: "true"
    Grid/NoiseFilteringRadius: "0.05"
    Grid/NoiseFilteringMinNeighbors: "3"
    Grid/NormalK: "30"
    Reg/Strategy: "0"
    Reg/Force3DoF: "true"
    RGBD/ProximityPathMaxNeighbors: "1"
    Rtabmap/TimeThr: "0"
    RGBD/OptimizeStrategy: "1"
    RGBD/LinearUpdate: "0.05"
    RGBD/AngularUpdate: "0.05"
    RGBD/LoopClosureReextractFeatures: "true"
    RGBD/LoopThr: "0.1"
    RGBD/LoopCovLimited: "true"
    Kp/DetectorStrategy: "0"
    Vis/FeatureType: "0"
    Vis/MinInliers: "15"
    Mem/UseOdomFeatures: "true"
    Mem/LaserScanVoxelSize: "0.015"
    Icp/PointToPlaneMinComplexity: "0.007"
    Icp/MaxCorrespondenceDistance: "0.05"
    Icp/CorrespondenceRatio: "0.2"
    Icp/PointToPlaneK: "20"
    RGBD/DepthDecimation: "1"
